
export const metadata = {
  title: 'APIXcel authentication',
  description: 'Generated by create next app',
}
export default function AuthLayout({ children }) {
  return (
    <>
      {children}
    </>
  )
}
